console.log("Better Rosario");

generateBtns();

const observeDOM = (function () {
  const MutationObserver = window.MutationObserver || window.WebKitMutationObserver;

  return function (obj, callback) {
    if (!obj || obj.nodeType !== 1) return;

    if (MutationObserver) {
      // define a new observer
      var mutationObserver = new MutationObserver(callback)

      // have the observer observe foo for changes in children
      mutationObserver.observe(obj, {childList: true, subtree: true})
      return mutationObserver
    }

    // browser support fallback
    else if (window.addEventListener) {
      obj.addEventListener('DOMNodeInserted', callback, false)
      obj.addEventListener('DOMNodeRemoved', callback, false)
    }
  }
})();

let agendaDiv = document.getElementsByClassName("viz_agenda")[0];
const btnsDiv = document.createElement("div");
btnsDiv.setAttribute("id", "autoGeneratedBtnsDiv")
agendaDiv.appendChild(btnsDiv);

function generateBtns() {
  const btns = document.getElementsByClassName("autoGeneratedBetterRosarioBtn");
  while (btns.length > 0) {
    btns[0].parentNode.removeChild(btns[0]);
  }

  setTimeout(() => {
    // get all elements with class autoGeneratedBetterRosarioBtn and remove them from the DOM
    const btns = document.getElementsByClassName("autoGeneratedBetterRosarioBtn");
    while (btns.length > 0) {
      btns[0].parentNode.removeChild(btns[0]);
    }

    let agendaUl = document.getElementsByClassName("lst_agendas")[0];
    let agendaLi = agendaUl.getElementsByTagName("li");

    // Set the innerHTML of each li in agendaLi
    for (let i = 0; i < agendaLi.length; i++) {
      
      let input = document.createElement("input");
      input.setAttribute("type", "button");
      input.setAttribute("class", "autoGeneratedBetterRosarioBtn");
      input.setAttribute("value", "Finalizar");

      input.innerHTML = agendaLi[i].id.split("_")[1];

      input.addEventListener("click", (inputElement) => {
        console.log("clicked", inputElement.target.innerHTML);
        console.log("inputElement", inputElement);
        document.getElementById("hddAgenda").value = inputElement.target.innerHTML;

        let btnFinalizar = document.getElementById("btnFinalizar");
        btnFinalizar.click();
        
        observeDOM(document.getElementsByClassName("lst_agendas")[0], () => {
          console.log("DOM observer changed")
          generateBtns();
        });
      });
      btnsDiv.appendChild(input);
    }

    const lis = document.getElementsByTagName("li");
    const btnVoltar = document.getElementById("btnVoltar");
    const btnFinalizar = document.getElementById("btnFinalizar");

    for (let i = 0; i < lis.length; i++) {
      lis[i].addEventListener("click", function() {
        console.log("generating btns");
        generateBtns();
      });
    }
    
    btnVoltar.addEventListener("click", function() {
      console.log("generating btns");
      generateBtns();
    });

    btnFinalizar.addEventListener("click", function() {
      console.log("generating btns");
      generateBtns();
    });
  }, 500);
}